backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "トップページ/共通コンテンツ"
      name: "home"
      file: "content/home.md"
      fields:
        - label: 'アプリ一覧'
          name: "apps"
          widget: list
          fields:
            - { label: "名称", name: "name", widget: "string"}
            - { label: "詳細", name: "description", widget: "text"}
        - label: 'サービス一覧'
          name: "services"
          widget: list
          fields:
            - { label: "名称", name: "name", widget: "string"}
            - { label: "詳細", name: "description", widget: "text"}
  - label: 'News'
    name: 'news'
    folder: 'content/news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string', required: true }
      - { label: '投稿日時', name: 'date', widget: 'datetime', required: true }
      - { label: 'サムネイル画像', name: 'thumbnail', widget: 'image', required: false }
      - { label: '本文', name: 'body', widget: 'markdown', required: true }
